language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

# define the order of the stages:
stages:
  - package
  - test
  - deploy

script:
  - cd ${TRAVIS_BUILD_DIR}/${MODULE}
  - mvn test -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end
#  - mvn failsafe:integration-test failsafe:verify -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

jobs:
  include:
    - stage: package
    - stage: deploy
      script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean deploy"
      skip_cleanup: true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"
  matrix:
    - MODULE=michalm                        
    - MODULE=jbischoff                        

cache:
  directories:
  - $HOME/.m2
