language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

# This skips the mvn install that is otherwise run (implausibly, the setting has to be "true")
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

# define the order of the stages:
stages:
  - package
  - test
  - deploy

script:
  - mvn install --also-make --projects ${MODULE} -DskipTests && cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn failsafe:integration-test failsafe:verify -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

jobs:
  include:
    - stage: package
      script: mvn package -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end
    - stage: deploy
      script: "mvn --settings .travis.settings.xml -DskipTests=true -B clean deploy"
      skip_cleanup: true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"
  matrix:
    - MODULE=vsp
    - MODULE=agarwalamit
    - MODULE=benjamin
    - MODULE=dgrether
    - MODULE=dziemke
    - MODULE=gleich
    - MODULE=gunnar
    - MODULE=ikaddoura
    - MODULE=jbischoff
    - MODULE=kai
    - MODULE=kairuns
    - MODULE=kturner
    - MODULE=michalm
    - MODULE=santiago
    - MODULE=stockholm
    - MODULE=tthunig
    - MODULE=vspshk
    - MODULE=vsptelematics
    
cache:
  directories:
  - $HOME/.m2
